"""
PkgConfig.py — Automatic pkg-config (.pc) file generation for FoBiS-built libraries.

Implements issue #179: generate a relocatable ``.pc`` file on build (uninstalled)
and on install (installed), making FoBiS-built Fortran libraries discoverable by
downstream pkg-config users.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

from . import __version__

# ---------------------------------------------------------------------------
# Spec dataclass
# ---------------------------------------------------------------------------


@dataclass
class PkgConfigSpec:
    """All metadata needed to generate a pkg-config file."""

    name: str
    version: str
    description: str
    url: str = ""
    requires: str = ""
    requires_priv: str = ""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


class PkgConfigGenerator:
    """Generate pkg-config ``.pc`` file content for a FoBiS-built library."""

    def generate(
        self,
        spec: PkgConfigSpec,
        lib_name: str,
        prefix: str,
        lib_dir: str = "lib",
        include_dir: str = "include",
    ) -> str:
        """
        Return the ``.pc`` file content as a string.

        Parameters
        ----------
        spec : PkgConfigSpec
        lib_name : str
            Name of the library file without prefix/suffix (e.g. ``'mylib'``).
        prefix : str
            Installation prefix; becomes the ``prefix=`` line.
        lib_dir : str
            Library subdirectory relative to prefix (default: ``'lib'``).
        include_dir : str
            Include subdirectory relative to prefix (default: ``'include'``).

        Returns
        -------
        str
        """
        # Strip leading 'v' from version for pkg-config consumers
        version = spec.version.lstrip("v") if spec.version else ""

        lines = [
            f"# Generated by FoBiS.py v{__version__}",
            f"prefix={prefix}",
            f"libdir=${{prefix}}/{lib_dir}",
            f"includedir=${{prefix}}/{include_dir}",
            "",
            f"Name: {spec.name}",
            f"Description: {spec.description}",
            f"Version: {version}",
        ]
        if spec.url:
            lines.append(f"URL: {spec.url}")
        if spec.requires:
            lines.append(f"Requires: {spec.requires}")
        if spec.requires_priv:
            lines.append(f"Requires.private: {spec.requires_priv}")

        # Strip leading 'lib' from library name for -l flag
        lname = lib_name
        for prefix_strip in ("lib",):
            if lname.startswith(prefix_strip):
                lname = lname[len(prefix_strip) :]
                break
        # Also strip common suffixes
        for suffix in (".a", ".so", ".dylib"):
            if lname.endswith(suffix):
                lname = lname[: -len(suffix)]
                break

        lines += [
            f"Libs: -L${{libdir}} -{'' if lname.startswith('l') else 'l'}{lname}",
            "Libs.private:",
            "Cflags: -I${includedir}",
        ]
        return "\n".join(lines) + "\n"

    def write(
        self,
        spec: PkgConfigSpec,
        lib_name: str,
        prefix: str,
        lib_dir: str,
        include_dir: str,
        output_path: str,
    ) -> None:
        """
        Write the ``.pc`` file to *output_path*.

        Parameters
        ----------
        spec : PkgConfigSpec
        lib_name : str
        prefix : str
        lib_dir : str
        include_dir : str
        output_path : str
        """
        content = self.generate(spec, lib_name, prefix, lib_dir, include_dir)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w") as f:
            f.write(content)
