#!/usr/bin/env bash
# setup.sh — build a small, self-contained FoBiS ecosystem for the `fobis ecosystem` demos.
#
# Usage: setup.sh DIR
#
# Creates in DIR three Fortran projects, each a git clone of a local bare "origin" in DIR/remotes:
#
#   core   <- mathx <- app        (app also uses core directly)
#
# with fetched dependencies (DIR/<project>/third_party, as `fobis fetch` leaves them), a v1.0.0 tag,
# a minimal scripts/release.sh, and some history after the tag:
#
#   core   feat(core): add halve()            -> releasable, minor bump; the dependents' locks are stale
#   mathx  docs: explain quadruple()          -> unreleased, nothing to release (docs only)
#   app    (nothing)                          -> up to date
#
# DIR/.config/fobis/config.ini registering them, and DIR/env.sh to source before running the demos
# (it selects that config and makes the demo's github.com/demo/* dependency URLs resolve to DIR/remotes).
# Nothing leaves DIR: the remotes are local, so releases are real but private.

set -euo pipefail

DIR="$(mkdir -p "$1" && cd "$1" && pwd)"
cd "$DIR"
mkdir -p remotes .config/fobis

git_q() { git -c commit.gpgsign=false -c tag.gpgSign=false -c init.defaultBranch=master "$@" >/dev/null 2>&1; }

write_release_script() {
  mkdir -p scripts
  cat > scripts/release.sh <<'EOF'
#!/usr/bin/env bash
# Minimal release script (the real ones also regenerate CHANGELOG.md with git-cliff).
set -euo pipefail
NEW_TAG="$1"
echo "  Current version : $(git describe --tags --abbrev=0)"
echo "  New version     : ${NEW_TAG}"
read -rp "Proceed? [y/N] " CONFIRM
[[ "${CONFIRM,,}" == "y" ]] || { echo "Aborted."; exit 0; }
echo "${NEW_TAG}" > VERSION
git add VERSION
git commit -q -m "chore(release): ${NEW_TAG}"
git tag -a "${NEW_TAG}" -m "Release ${NEW_TAG}"
git push -q origin master --follow-tags
echo "Released ${NEW_TAG}!"
EOF
  chmod +x scripts/release.sh
}

new_project() {  # new_project NAME
  git_q init --bare "remotes/$1.git"
  git_q clone "remotes/$1.git" "$1"
  git -C "$1" config user.name "Demo"
  git -C "$1" config user.email "demo@example.com"
  git -C "$1" config commit.gpgsign false
  git -C "$1" config tag.gpgSign false
}

scaffold() {  # scaffold NAME: the boilerplate `fobis scaffold init` creates (CI, docs, scripts)
  (cd "$1" && fobis scaffold init --yes </dev/null >/dev/null 2>&1)
}

commit_all() {  # commit_all NAME MESSAGE
  git -C "$1" add -A
  git_q -C "$1" commit -m "$2"
}

fetch_dep() {  # fetch_dep PROJECT DEP...: what `fobis fetch` would leave in third_party
  local project="$1"; shift
  mkdir -p "$project/third_party"
  local src="" lock="# fobos.lock — auto-generated by FoBiS.py fetch — do not edit by hand"$'\n'
  for dep in "$@"; do
    rm -rf "$project/third_party/$dep"
    git_q clone "remotes/$dep.git" "$project/third_party/$dep"
    src+=" third_party/$dep"
    lock+=$'\n'"[$dep]"$'\n'"url = https://github.com/demo/$dep"$'\n'"commit = $(git -C "$project/third_party/$dep" rev-parse HEAD)"$'\n'
  done
  printf '[deps]\nsrc =%s\n' "$src" > "$project/third_party/.deps_config.ini"
  printf '%s' "$lock" > "$project/third_party/fobos.lock"
}

# ── core ──────────────────────────────────────────────────────────────────────
new_project core
mkdir -p core/src
cat > core/src/core_m.f90 <<'EOF'
module core_m
  implicit none
  private
  public :: twice
contains
  elemental function twice(x) result(y)
    real, intent(in) :: x
    real :: y
    y = 2.0 * x
  end function twice
end module core_m
EOF
cat > core/src/test_core.f90 <<'EOF'
program test_core
  use core_m, only: twice
  implicit none
  if (twice(2.0) /= 4.0) error stop "twice(2) /= 4"
  print '(A)', "core: all tests passed"
end program test_core
EOF
cat > core/fobos <<'EOF'
[project]
name    = core
summary = Tiny core library of the demo ecosystem

[default]
compiler  = gnu
cflags    = -c
src       = src
build_dir = build
target    = src/test_core.f90
output    = test_core

[scaffold]
skip = scripts/release.sh

[ecosystem]
check = fobis build
        ./build/test_core
EOF
echo "v1.0.0" > core/VERSION
printf 'build/\n' > core/.gitignore
(cd core && write_release_script)
scaffold core
commit_all core "feat(core): first release"
git_q -C core tag -a v1.0.0 -m "Release v1.0.0"
git_q -C core push origin master --follow-tags

# ── mathx (uses core) ─────────────────────────────────────────────────────────
new_project mathx
mkdir -p mathx/src
cat > mathx/src/mathx_m.f90 <<'EOF'
module mathx_m
  use core_m, only: twice
  implicit none
  private
  public :: quadruple
contains
  elemental function quadruple(x) result(y)
    real, intent(in) :: x
    real :: y
    y = twice(twice(x))
  end function quadruple
end module mathx_m
EOF
cat > mathx/src/test_mathx.f90 <<'EOF'
program test_mathx
  use mathx_m, only: quadruple
  implicit none
  if (quadruple(1.5) /= 6.0) error stop "quadruple(1.5) /= 6"
  print '(A)', "mathx: all tests passed"
end program test_mathx
EOF
cat > mathx/fobos <<'EOF'
[project]
name    = mathx
summary = Math extensions built on core

[dependencies]
deps_dir = third_party
core     = https://github.com/demo/core

[default]
compiler  = gnu
cflags    = -c
src       = src
build_dir = build
target    = src/test_mathx.f90
output    = test_mathx

[scaffold]
skip = scripts/release.sh

[ecosystem]
check = fobis build
        ./build/test_mathx
EOF
echo "v1.0.0" > mathx/VERSION
printf 'build/\nthird_party/\n' > mathx/.gitignore
echo "# mathx" > mathx/README.md
(cd mathx && write_release_script)
scaffold mathx
commit_all mathx "feat(mathx): first release"
git_q -C mathx tag -a v1.0.0 -m "Release v1.0.0"
git_q -C mathx push origin master --follow-tags

# ── app (uses mathx and core) ─────────────────────────────────────────────────
new_project app
mkdir -p app/src
cat > app/src/app.f90 <<'EOF'
program app
  use core_m,  only: twice
  use mathx_m, only: quadruple
  implicit none
  print '(A,F5.1,A,F5.1)', "twice(3) =", twice(3.0), "   quadruple(3) =", quadruple(3.0)
end program app
EOF
cat > app/fobos <<'EOF'
[project]
name    = app
summary = Application of the demo ecosystem

[dependencies]
deps_dir = third_party
mathx    = https://github.com/demo/mathx
core     = https://github.com/demo/core

[default]
compiler  = gnu
cflags    = -c
src       = src
build_dir = build
target    = src/app.f90
output    = app

[scaffold]
skip = scripts/release.sh

[ecosystem]
check = fobis build
        ./build/app
EOF
echo "v1.0.0" > app/VERSION
printf 'build/\nthird_party/\n' > app/.gitignore
(cd app && write_release_script)
scaffold app
commit_all app "feat(app): first release"
git_q -C app tag -a v1.0.0 -m "Release v1.0.0"
git_q -C app push origin master --follow-tags

# ── dependencies as fetched at release time ──────────────────────────────────
fetch_dep mathx core
fetch_dep app mathx core

# ── history after the releases ───────────────────────────────────────────────
cat > core/src/core_m.f90 <<'EOF'
module core_m
  implicit none
  private
  public :: twice, halve
contains
  elemental function twice(x) result(y)
    real, intent(in) :: x
    real :: y
    y = 2.0 * x
  end function twice

  elemental function halve(x) result(y)
    real, intent(in) :: x
    real :: y
    y = 0.5 * x
  end function halve
end module core_m
EOF
commit_all core "feat(core): add halve()"
git_q -C core push origin master

printf '# mathx\n\n`quadruple(x)` is `twice(twice(x))`.\n' > mathx/README.md
commit_all mathx "docs: explain quadruple()"
git_q -C mathx push origin master

# ── user configuration registering the three projects ────────────────────────
cat > .config/fobis/config.ini <<EOF
[ecosystem]
root     = ${DIR}
projects = core mathx app
EOF

# ── environment: the demo config, and github.com/demo/* rewritten to the local remotes ────
# (git's url.<base>.insteadOf: `fobis fetch` then clones the demo dependencies from DIR/remotes)
cat > env.sh <<EOF
export XDG_CONFIG_HOME="${DIR}/.config"
export GIT_CONFIG_COUNT=1
export GIT_CONFIG_KEY_0="url.${DIR}/remotes/.insteadOf"
export GIT_CONFIG_VALUE_0="https://github.com/demo/"
EOF

echo "Demo ecosystem ready in ${DIR}"
echo "  source ${DIR}/env.sh"
